name: singlecell-dash
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- cycler
- decorator
- freetype
- icu
- ipython_genutils
- jsonschema
- jupyter_core
- libpng
- matplotlib
- mkl
- nbformat
- numpy
- openssl
- pandas
- pip
- plotly
- pyparsing
- pyqt
- python=3.6
- python-dateutil
- pytz
- qt
- readline
- requests
- scipy
- seaborn
- setuptools
- sip
- six
- sqlite
- scikit-learn
- tk
- traitlets
- wheel
- xz
- zlib
- pip:
  - click
  - colorlover
  - dash>=0.17.7
  - dash_core_components==0.10rc1
  - dash-html-components>=0.6.2
  - dash-renderer>=0.7.3
  - flask
  - flask-compress
  - flask-seasurf
  - ipython-genutils
  - itsdangerous
  - jinja2
  - jupyter-core
  - markupsafe
  - werkzeug
